baseURL = "https://www.yagerre.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.footer]]
name = "Search Homes"
url = "https://search.idxhome.com/homesearch/150102"
weight = 2
[[menu.main]]
name = "Property Search"
url = "https://search.yagerre.com/homesearch/150102"
weight = 2
[[menu.main]]
name = "Home Valuation"
parent = "Sell"
url = "/home-value-request"
weight = 3
[[menu.main]]
name = "Mortgage Calculator"
parent = "Buy"
url = "https://search.yagerre.com/mortcalc/133407"
weight = 2
[[menu.main]]
name = "Our Sales"
parent = "Portfolio"
url = "http://search.yagerre.com/listing/supplementals/150102"
weight = 2
[[menu.main]]
name = "Portfolio"
weight = 6
[[menu.main]]
name = "Communities"
weight = 5
[[menu.main]]
name = "Buy"
weight = 4
[[menu.main]]
name = "Sell"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
city = "cities"
featured = "featured"
property = "properties"
state = "states"
status = "status"
tag = "tags"
zip = "zip-codes"
